#!/bin/bash
# load-csi-stack.sh — switch wlan0 to nexmon CSI monitor mode.
#
# Uses reboot-based firmware swap (safer than live modprobe; live driver
# reload has been known to soft-hang the Pi 4 when the chip is in monitor
# mode + active capture). Auto-revert via cron after 15 min if not committed.
#
# Usage: sudo ./load-csi-stack.sh [channel] [bandwidth]
#   channel:   integer (default 36)
#   bandwidth: NOHT|HT20|HT40+|HT40-|80MHz|160MHz (default NOHT = 20 MHz)
#
# After reboot, run:
#   sudo iw dev wlan0 set type monitor
#   sudo iw dev wlan0 set channel <CH> <BW>
#   sudo nexutil -Iwlan0 -m1
#   sudo tcpdump -i wlan0 -w cap.pcap
set -eu

CHANNEL=${1:-36}
BANDWIDTH=${2:-NOHT}

if [[ $EUID -ne 0 ]]; then
    echo "must be run as root: sudo $0 [channel] [bandwidth]" >&2
    exit 1
fi

KERNEL=$(uname -r)
DRIVER_TARGET="/lib/modules/$KERNEL/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/brcmfmac.ko.xz"

# 1. update-alternatives → nexmon firmware
echo "[1/4] Activating nexmon firmware..."
update-alternatives --quiet --set cyfmac43455-sdio.bin \
    /lib/firmware/nexmon/brcmfmac43455-sdio.bin

# 2. Install modified brcmfmac driver if needed
WANT_MD5="7957d8d72c74b1bf828dd012e1c1cc6a"
HAVE_MD5=$(md5sum "$DRIVER_TARGET" | cut -d" " -f1)
if [[ "$HAVE_MD5" != "$WANT_MD5" ]]; then
    echo "[2/4] Installing modified brcmfmac driver..."
    BUNDLED="$(dirname "$0")/driver/brcmfmac.ko.xz"
    if [[ -f "$BUNDLED" ]]; then
        cp "$BUNDLED" "$DRIVER_TARGET"
        depmod -a
    else
        echo "  WARNING: bundled driver not found at $BUNDLED"
    fi
else
    echo "[2/4] Modified brcmfmac already installed."
fi

# 3. Save the post-boot setup command for the user
cat > /etc/profile.d/csi-mode-tip.sh <<TIP
# Auto-generated by load-csi-stack.sh
if [[ "\$(tty)" == "/dev/pts/0" ]] || [[ -n "\${SSH_CLIENT:-}" ]]; then
    if md5sum /lib/firmware/cypress/cyfmac43455-sdio.bin 2>/dev/null | grep -q dcf871872d; then
        echo
        echo "[ NEXMON CSI MODE ACTIVE ]"
        echo "  Activate monitor capture:"
        echo "    sudo iw dev wlan0 set type monitor"
        echo "    sudo iw dev wlan0 set channel $CHANNEL $BANDWIDTH"
        echo "    sudo nexutil -Iwlan0 -m1"
        echo "    sudo tcpdump -i wlan0 -w cap.pcap"
        echo "  Restore stock WiFi: sudo $(dirname "$0")/restore-stock.sh && sudo reboot"
        echo
    fi
fi
TIP
chmod 644 /etc/profile.d/csi-mode-tip.sh

# 4. Reboot for safe firmware swap
echo "[3/4] Firmware staged. Need reboot to load nexmon firmware."
echo "[4/4] System will reboot in 5 seconds. Cancel with Ctrl-C."
sleep 5
reboot
